displayName=Area Darkener
author=Jacob
description=Darkens configurable areas of bright terrain and scenery to reduce glare
tags=dark,area,terrain,wintertodt,gwd,huey,hueycoatl,vorkath,graphics
version=1
plugins=com.hueydarkener.HueyDarkenerPlugin
build=standard
