displayName=Darkener
author=Jacob
description=Darkens bright terrain and scenery colors to reduce glare
tags=dark,terrain,wintertodt,gwd,huey,hueycoatl,vorkath,graphics
version=1
plugins=com.hueydarkener.HueyDarkenerPlugin
build=standard
